### ISSUE TITLE
A statement regarding "Patch Monterey"

### ISSUE THREAD

**Issue by Finder352** [Solomon-Wood/Patch-Monterey#1]
If your not aware, the CLI patcher that @BenSova will be developing is something that will evolve into a full UI patcher called "Patched Monterey".  The CLI patcher is just a stepping stone to that and is only temporary.

**Comment by Solomon-Wood** [comment]
I am aware of this. When @BenSova archives the CLI Patcher, I will then continue to maintain that.

**Comment by AvaQueen-Official** [comment]
What the f**k are you talking about, you are still using Ben's repos!

**Comment by Monkiey** [comment]
> What the f**k are you talking about, you are still using Ben's repos!

yep and the UI for patch Monterey or whatever this silly rip off is ridiculous and it does nothing but confuse the user and is postally dangerous due to bugs

**Comment by Monkiey** [comment]
this is lines for Ben to issue a DMCA takedown of this silly repo that is clearly a rip of Ben Repos and patches
